apiVersion: v1
data:
  kdc.conf: |+
    includedir /var/lib/krb5kdc.d
    
    [logging]
    default = STDERR
    
    [kdcdefaults]
      kdc_listen = 8888
      kdc_tcp_ports = 8888
      kadmind_port = 8749
      kpasswd_port = 8464
      
    }
kind: ConfigMap
metadata:
  name: kdc-config
---
apiVersion: v1
data:
  krb5.conf: |+
    includedir /etc/krb5.conf.d/
    [logging]
    default = STDERR
    
    [libdefaults]
    default_ccache_name=FILE:/dev/shm/ccache
    default_client_keytab_name=/krb5/client.keytab
    default_keytab_name=/krb5/krb5.keytab
    rdns = false
    ignore_acceptor_hostname = true
kind: ConfigMap
metadata:
  name: krb5-config